name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  pull_request:
      

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20"
      - name: Run lint
        run: |
          make lint
      - name: Run build
        run: |
          make build
  release:
    name: release
    if: startsWith(github.ref, 'refs/tags')
    needs: lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: [linux, freebsd, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: "arm64"
            goos: freebsd
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: https://go.dev/dl/go1.20.8.linux-amd64.tar.gz
          pre_command: export CGO_ENABLED=0
          compress_assets: OFF
          binary_name: smart-kill
          build_command: make
          sha256sum: TRUE
          md5sum: FALSE